spring:
  application:
    name: namul
  profiles:
    active: local
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DB_NAME}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      authentication-database: admin

upstage:
  api-key: ${UPSTAGE_API_KEY}
  base-url: https://api.upstage.ai/v1
