spring:
  application:
    name: namul
  ai:
    openai:
      api-key: ${API_KEY}
  profiles:
    active: local
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: admin
      authentication-database: admin
springdoc:
  api-docs:
    enabled: true

upstage:
  base-url: https://api.upstage.ai/v1
